### ISSUE TITLE
NRE in SqlGeography.Null.ToString()

### ISSUE THREAD

**Issue by MaceWindu** [dotMorten/Microsoft.SqlServer.Types#14]
`SqlGeography.Null.ToString()` throws NRE due to ShapeData._shapes being null:
```cs
Result StackTrace:	
at Microsoft.SqlServer.Types.ShapeData.get_Type() in c:\GitHub\Microsoft.SqlServer.Types\src\Microsoft.SqlServer.Types\ShapeData.cs:line 110
   at Microsoft.SqlServer.Types.WktWriter.WriteGeometry(ShapeData geometry, StringBuilder sb, Boolean includeZ, Boolean includeM) in c:\GitHub\Microsoft.SqlServer.Types\src\Microsoft.SqlServer.Types\Wkt\WktWriter.cs:line 41
   at Microsoft.SqlServer.Types.WktWriter.Write(ShapeData g, Boolean includeZ, Boolean includeM) in c:\GitHub\Microsoft.SqlServer.Types\src\Microsoft.SqlServer.Types\Wkt\WktWriter.cs:line 35
   at Microsoft.SqlServer.Types.WktWriter.Write(ShapeData g) in c:\GitHub\Microsoft.SqlServer.Types\src\Microsoft.SqlServer.Types\Wkt\WktWriter.cs:line 22
   at Microsoft.SqlServer.Types.SqlGeography.ToString() in c:\GitHub\Microsoft.SqlServer.Types\src\Microsoft.SqlServer.Types\SqlGeography.cs:line 462
   at Tests.DataProvider.SqlServerTests.TestGeography(String context) in c:\GitHub\linq2db\Tests\Linq\DataProvider\SqlServerTests.cs:line 660
Result Message:	System.NullReferenceException : Object reference not set to an instance of an object.

```

**Comment by dotMorten** [comment]
Thanks! Fixed
